/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface GlobalLeaderboardEntry {
  'username' : string,
  'player' : Principal,
  'totalWinnings' : bigint,
  'totalScore' : bigint,
}
export interface LeaderboardEntry {
  'player' : Principal,
  'score' : bigint,
  'tournamentId' : bigint,
}
export type Time = bigint;
export interface Tournament {
  'id' : bigint,
  'categoryId' : bigint,
  'status' : TournamentStatus,
  'prizeDistribution' : Array<bigint>,
  'title' : string,
  'totalSlots' : bigint,
  'entryFee' : bigint,
  'slotsFilled' : bigint,
  'rules' : string,
  'prizePool' : bigint,
}
export type TournamentStatus = { 'active' : null } |
  { 'upcoming' : null } |
  { 'completed' : null };
export interface Transaction {
  'id' : bigint,
  'user' : Principal,
  'txnType' : { 'deposit' : null } |
    { 'withdrawal' : null } |
    { 'tournamentEntry' : null },
  'timestamp' : Time,
  'amount' : bigint,
}
export interface UserProfile { 'username' : string, 'balance' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoins' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createTournament' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, string, Array<bigint>],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<GlobalLeaderboardEntry>>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getTakenSlots' : ActorMethod<[bigint], Array<bigint>>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint, bigint], undefined>,
  'postScores' : ActorMethod<[bigint, Array<[Principal, bigint]>], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];