/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
  'tournamentId' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : TournamentStatus,
  'prizeDistribution' : IDL.Vec(IDL.Nat),
  'title' : IDL.Text,
  'totalSlots' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'slotsFilled' : IDL.Nat,
  'rules' : IDL.Text,
  'prizePool' : IDL.Nat,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'txnType' : IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'tournamentEntry' : IDL.Null,
  }),
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'postScores' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      [],
      [],
    ),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'score' : IDL.Nat,
    'tournamentId' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : TournamentStatus,
    'prizeDistribution' : IDL.Vec(IDL.Nat),
    'title' : IDL.Text,
    'totalSlots' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'slotsFilled' : IDL.Nat,
    'rules' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'txnType' : IDL.Variant({
      'deposit' : IDL.Null,
      'withdrawal' : IDL.Null,
      'tournamentEntry' : IDL.Null,
    }),
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'postScores' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        [],
        [],
      ),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };