/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DepositRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'paymentMethod' : IDL.Variant({
    'easyPaisa' : IDL.Null,
    'jazzCash' : IDL.Null,
  }),
  'transactionReference' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const GlobalLeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'player' : IDL.Principal,
  'totalWinnings' : IDL.Nat,
  'totalScore' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
  'tournamentId' : IDL.Nat,
});
export const PaymentNumbers = IDL.Record({
  'easyPaisa' : IDL.Text,
  'jazzCash' : IDL.Text,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : TournamentStatus,
  'prizeDistribution' : IDL.Vec(IDL.Nat),
  'title' : IDL.Text,
  'totalSlots' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'slotsFilled' : IDL.Nat,
  'rules' : IDL.Text,
  'prizePool' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'txnType' : IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'tournamentEntry' : IDL.Null,
  }),
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getGlobalLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(GlobalLeaderboardEntry)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getPaymentNumbers' : IDL.Func([], [PaymentNumbers], ['query']),
  'getPendingDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'postScores' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      [],
      [],
    ),
  'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentNumbers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'submitDepositRequest' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({ 'easyPaisa' : IDL.Null, 'jazzCash' : IDL.Null }),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DepositRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'paymentMethod' : IDL.Variant({
      'easyPaisa' : IDL.Null,
      'jazzCash' : IDL.Null,
    }),
    'transactionReference' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const GlobalLeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'player' : IDL.Principal,
    'totalWinnings' : IDL.Nat,
    'totalScore' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'score' : IDL.Nat,
    'tournamentId' : IDL.Nat,
  });
  const PaymentNumbers = IDL.Record({
    'easyPaisa' : IDL.Text,
    'jazzCash' : IDL.Text,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : TournamentStatus,
    'prizeDistribution' : IDL.Vec(IDL.Nat),
    'title' : IDL.Text,
    'totalSlots' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'slotsFilled' : IDL.Nat,
    'rules' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'txnType' : IDL.Variant({
      'deposit' : IDL.Null,
      'withdrawal' : IDL.Null,
      'tournamentEntry' : IDL.Null,
    }),
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getGlobalLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(GlobalLeaderboardEntry)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPaymentNumbers' : IDL.Func([], [PaymentNumbers], ['query']),
    'getPendingDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'postScores' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        [],
        [],
      ),
    'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentNumbers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'submitDepositRequest' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'easyPaisa' : IDL.Null, 'jazzCash' : IDL.Null }),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };