/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const ExtendedUserProfile = IDL.Record({
  'inGameName' : IDL.Text,
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'legendId' : IDL.Nat,
  'referCode' : IDL.Text,
  'mobileNo' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'gameUID' : IDL.Text,
});

export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'active' : IDL.Null,
  'completed' : IDL.Null,
});

export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : TournamentStatus,
  'prizeDistribution' : IDL.Vec(IDL.Nat),
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'totalSlots' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'slotsFilled' : IDL.Nat,
  'rules' : IDL.Text,
  'prizePool' : IDL.Nat,
});

export const PaymentMethod = IDL.Variant({
  'jazzCash' : IDL.Null,
  'easyPaisa' : IDL.Null,
});

export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});

export const DepositRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'paymentMethod' : PaymentMethod,
  'transactionReference' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const TxnType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'tournamentEntry' : IDL.Null,
});

export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'txnType' : TxnType,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const LeaderboardEntry = IDL.Record({
  'tournamentId' : IDL.Nat,
  'player' : IDL.Principal,
  'score' : IDL.Nat,
});

export const GlobalLeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'username' : IDL.Text,
  'totalScore' : IDL.Nat,
  'totalWinnings' : IDL.Nat,
});

export const PaymentNumbers = IDL.Record({
  'easyPaisa' : IDL.Text,
  'jazzCash' : IDL.Text,
});

export const RoomDetails = IDL.Record({
  'roomId' : IDL.Text,
  'roomPassword' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addCoinsByLegendId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createTournament' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text], [], []),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Principal, ExtendedUserProfile))], []),
  'getAllWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getCallerDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getCallerJoinedSlot' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ExtendedUserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(GlobalLeaderboardEntry)], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getPaymentNumbers' : IDL.Func([], [PaymentNumbers], ['query']),
  'getPendingDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getPendingWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getResetCode' : IDL.Func([], [IDL.Text], ['query']),
  'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentRoomDetails' : IDL.Func([IDL.Nat], [IDL.Opt(RoomDetails)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserByLegendId' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Tuple(IDL.Principal, ExtendedUserProfile))], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(ExtendedUserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : ExtendedUserProfile, 'err' : IDL.Text })], []),
  'loginByLegendId' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Variant({ 'ok' : ExtendedUserProfile, 'err' : IDL.Text })], []),
  'postScores' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))], [], []),
  'registerAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'removeCoinsByLegendId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
  'resetPasswordByLegendId' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
  'saveCallerUserProfile' : IDL.Func([ExtendedUserProfile], [], []),
  'setPaymentNumbers' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setResetCode' : IDL.Func([IDL.Text], [], []),
  'setTournamentRoomDetails' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'submitDepositRequest' : IDL.Func([IDL.Nat, PaymentMethod, IDL.Text], [IDL.Nat], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'updateUserInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null, 'guest' : IDL.Null });
  const ExtendedUserProfile = IDL.Record({
    'inGameName' : IDL.Text, 'username' : IDL.Text, 'balance' : IDL.Nat,
    'legendId' : IDL.Nat, 'referCode' : IDL.Text, 'mobileNo' : IDL.Text,
    'fullName' : IDL.Text, 'email' : IDL.Text, 'gameUID' : IDL.Text,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const TournamentStatus = IDL.Variant({ 'upcoming' : IDL.Null, 'active' : IDL.Null, 'completed' : IDL.Null });
  const Tournament = IDL.Record({
    'id' : IDL.Nat, 'categoryId' : IDL.Nat, 'status' : TournamentStatus,
    'prizeDistribution' : IDL.Vec(IDL.Nat), 'title' : IDL.Text, 'imageUrl' : IDL.Text,
    'totalSlots' : IDL.Nat, 'entryFee' : IDL.Nat, 'slotsFilled' : IDL.Nat,
    'rules' : IDL.Text, 'prizePool' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({ 'jazzCash' : IDL.Null, 'easyPaisa' : IDL.Null });
  const RequestStatus = IDL.Variant({ 'pending' : IDL.Null, 'approved' : IDL.Null, 'rejected' : IDL.Null });
  const DepositRequest = IDL.Record({
    'id' : IDL.Nat, 'status' : RequestStatus, 'paymentMethod' : PaymentMethod,
    'transactionReference' : IDL.Text, 'user' : IDL.Principal, 'timestamp' : IDL.Int, 'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat, 'status' : RequestStatus, 'user' : IDL.Principal, 'timestamp' : IDL.Int, 'amount' : IDL.Nat,
  });
  const TxnType = IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null, 'tournamentEntry' : IDL.Null });
  const Transaction = IDL.Record({
    'id' : IDL.Nat, 'user' : IDL.Principal, 'txnType' : TxnType, 'timestamp' : IDL.Int, 'amount' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({ 'tournamentId' : IDL.Nat, 'player' : IDL.Principal, 'score' : IDL.Nat });
  const GlobalLeaderboardEntry = IDL.Record({
    'player' : IDL.Principal, 'username' : IDL.Text, 'totalScore' : IDL.Nat, 'totalWinnings' : IDL.Nat,
  });
  const PaymentNumbers = IDL.Record({ 'easyPaisa' : IDL.Text, 'jazzCash' : IDL.Text });
  const RoomDetails = IDL.Record({ 'roomId' : IDL.Text, 'roomPassword' : IDL.Text });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addCoinsByLegendId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createTournament' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text], [], []),
    'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Principal, ExtendedUserProfile))], []),
    'getAllWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getCallerDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getCallerJoinedSlot' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ExtendedUserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(GlobalLeaderboardEntry)], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getPaymentNumbers' : IDL.Func([], [PaymentNumbers], ['query']),
    'getPendingDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getPendingWithdrawalRequests' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getResetCode' : IDL.Func([], [IDL.Text], ['query']),
    'getTakenSlots' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentRoomDetails' : IDL.Func([IDL.Nat], [IDL.Opt(RoomDetails)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserByLegendId' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Tuple(IDL.Principal, ExtendedUserProfile))], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(ExtendedUserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : ExtendedUserProfile, 'err' : IDL.Text })], []),
    'loginByLegendId' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Variant({ 'ok' : ExtendedUserProfile, 'err' : IDL.Text })], []),
    'postScores' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))], [], []),
    'registerAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'removeCoinsByLegendId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
    'resetPasswordByLegendId' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
    'saveCallerUserProfile' : IDL.Func([ExtendedUserProfile], [], []),
    'setPaymentNumbers' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setResetCode' : IDL.Func([IDL.Text], [], []),
    'setTournamentRoomDetails' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'submitDepositRequest' : IDL.Func([IDL.Nat, PaymentMethod, IDL.Text], [IDL.Nat], []),
    'submitWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'updateUserInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
