/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    id: bigint;
    user: Principal;
    txnType: Variant_deposit_withdrawal_tournamentEntry;
    timestamp: Time;
    amount: bigint;
}
export interface LeaderboardEntry {
    player: Principal;
    score: bigint;
    tournamentId: bigint;
}
export interface ExtendedUserProfile {
    inGameName: string;
    username: string;
    balance: bigint;
    legendId: bigint;
    referCode: string;
    mobileNo: string;
    fullName: string;
    email: string;
    gameUID: string;
}
export type Time = bigint;
export interface GlobalLeaderboardEntry {
    username: string;
    player: Principal;
    totalWinnings: bigint;
    totalScore: bigint;
}
export interface Tournament {
    id: bigint;
    categoryId: bigint;
    status: TournamentStatus;
    prizeDistribution: Array<bigint>;
    title: string;
    imageUrl: string;
    totalSlots: bigint;
    entryFee: bigint;
    slotsFilled: bigint;
    rules: string;
    prizePool: bigint;
}
export interface DepositRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    paymentMethod: Variant_easyPaisa_jazzCash;
    transactionReference: string;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface WithdrawalRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface PaymentNumbers {
    easyPaisa: string;
    jazzCash: string;
}
export interface Category {
    id: bigint;
    name: string;
}
export enum TournamentStatus {
    active = "active",
    upcoming = "upcoming",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_deposit_withdrawal_tournamentEntry {
    deposit = "deposit",
    withdrawal = "withdrawal",
    tournamentEntry = "tournamentEntry"
}
export enum Variant_easyPaisa_jazzCash {
    easyPaisa = "easyPaisa",
    jazzCash = "jazzCash"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoins(user: Principal, amount: bigint): Promise<void>;
    addCoinsByLegendId(legendId: bigint, amount: bigint): Promise<void>;
    approveDepositRequest(requestId: bigint): Promise<void>;
    approveWithdrawalRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(name: string): Promise<void>;
    createTournament(title: string, categoryId: bigint, entryFee: bigint, prizePool: bigint, totalSlots: bigint, rules: string, prizeDistribution: Array<bigint>, imageUrl: string): Promise<void>;
    getAllDepositRequests(): Promise<Array<DepositRequest>>;
    getAllUsers(): Promise<Array<[Principal, ExtendedUserProfile]>>;
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCallerDepositRequests(): Promise<Array<DepositRequest>>;
    getCallerJoinedSlot(tournamentId: bigint): Promise<bigint | null>;
    getCallerUserProfile(): Promise<ExtendedUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCategories(): Promise<Array<Category>>;
    getGlobalLeaderboard(): Promise<Array<GlobalLeaderboardEntry>>;
    getLeaderboard(tournamentId: bigint): Promise<Array<LeaderboardEntry>>;
    getNextLegendId(): Promise<bigint>;
    getPaymentNumbers(): Promise<PaymentNumbers>;
    getPendingDepositRequests(): Promise<Array<DepositRequest>>;
    getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getResetCode(): Promise<string>;
    getTakenSlots(tournamentId: bigint): Promise<Array<bigint>>;
    getTournament(id: bigint): Promise<Tournament | null>;
    getTournamentRoomDetails(tournamentId: bigint): Promise<{
        roomPassword: string;
        roomId: string;
    } | null>;
    getTournaments(): Promise<Array<Tournament>>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUserByLegendId(legendId: bigint): Promise<[Principal, ExtendedUserProfile] | null>;
    getUserProfile(user: Principal): Promise<ExtendedUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: bigint, slotNumber: bigint): Promise<void>;
    login(email: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loginByLegendId(legendId: bigint, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    postScores(tournamentId: bigint, scores: Array<[Principal, bigint]>): Promise<void>;
    registerAccount(email: string, passwordHash: string, fullName: string, inGameName: string, gameUID: string, mobileNo: string, referCode: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(fullName: string, inGameName: string, gameUID: string, mobileNo: string, email: string, referCode: string): Promise<void>;
    rejectDepositRequest(requestId: bigint): Promise<void>;
    rejectWithdrawalRequest(requestId: bigint): Promise<void>;
    removeCoinsByLegendId(legendId: bigint, amount: bigint): Promise<void>;
    resetPassword(email: string, resetCode: string, newPasswordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetPasswordByLegendId(legendId: bigint, resetCode: string, newPasswordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: ExtendedUserProfile): Promise<void>;
    setPaymentNumbers(jazzCash: string, easyPaisa: string): Promise<void>;
    setResetCode(code: string): Promise<void>;
    setTournamentRoomDetails(tournamentId: bigint, roomId: string, roomPassword: string): Promise<void>;
    setUsername(username: string): Promise<void>;
    submitDepositRequest(amount: bigint, paymentMethod: Variant_easyPaisa_jazzCash, transactionReference: string): Promise<bigint>;
    submitWithdrawalRequest(amount: bigint): Promise<bigint>;
    updateUserInfo(fullName: string, inGameName: string, gameUID: string, mobileNo: string, email: string): Promise<void>;
}
import type { DepositRequest as _DepositRequest, ExtendedUserProfile as _ExtendedUserProfile, Time as _Time, Tournament as _Tournament, TournamentStatus as _TournamentStatus, Transaction as _Transaction, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoins(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoins(arg0, arg1);
            return result;
        }
    }
    async addCoinsByLegendId(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoinsByLegendId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoinsByLegendId(arg0, arg1);
            return result;
        }
    }
    async approveDepositRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDepositRequest(arg0);
            return result;
        }
    }
    async approveWithdrawalRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawalRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string, arg6: Array<bigint>, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async getAllDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepositRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepositRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, ExtendedUserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDepositRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDepositRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerJoinedSlot(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerJoinedSlot(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerJoinedSlot(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<ExtendedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWithdrawalRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWithdrawalRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getGlobalLeaderboard(): Promise<Array<GlobalLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLeaderboard();
            return result;
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getNextLegendId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextLegendId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextLegendId();
            return result;
        }
    }
    async getPaymentNumbers(): Promise<PaymentNumbers> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentNumbers();
            return result;
        }
    }
    async getPendingDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDepositRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDepositRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawalRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawalRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResetCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getResetCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResetCode();
            return result;
        }
    }
    async getTakenSlots(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTakenSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTakenSlots(arg0);
            return result;
        }
    }
    async getTournament(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentRoomDetails(arg0: bigint): Promise<{
        roomPassword: string;
        roomId: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentRoomDetails(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentRoomDetails(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByLegendId(arg0: bigint): Promise<[Principal, ExtendedUserProfile] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByLegendId(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByLegendId(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<ExtendedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinTournament(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0, arg1);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginByLegendId(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginByLegendId(arg0, arg1);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginByLegendId(arg0, arg1);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async postScores(arg0: bigint, arg1: Array<[Principal, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postScores(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postScores(arg0, arg1);
            return result;
        }
    }
    async registerAccount(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async rejectDepositRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDepositRequest(arg0);
            return result;
        }
    }
    async rejectWithdrawalRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawalRequest(arg0);
            return result;
        }
    }
    async removeCoinsByLegendId(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCoinsByLegendId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCoinsByLegendId(arg0, arg1);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1, arg2);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1, arg2);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordByLegendId(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordByLegendId(arg0, arg1, arg2);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordByLegendId(arg0, arg1, arg2);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: ExtendedUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setPaymentNumbers(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentNumbers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentNumbers(arg0, arg1);
            return result;
        }
    }
    async setResetCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setResetCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setResetCode(arg0);
            return result;
        }
    }
    async setTournamentRoomDetails(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTournamentRoomDetails(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTournamentRoomDetails(arg0, arg1, arg2);
            return result;
        }
    }
    async setUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0);
            return result;
        }
    }
    async submitDepositRequest(arg0: bigint, arg1: Variant_easyPaisa_jazzCash, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositRequest(arg0, to_candid_variant_n29(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositRequest(arg0, to_candid_variant_n29(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0);
            return result;
        }
    }
    async updateUserInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserInfo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserInfo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_DepositRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequest): DepositRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedUserProfile]): ExtendedUserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        roomPassword: string;
        roomId: string;
    }]): {
    roomPassword: string;
    roomId: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[Principal, _ExtendedUserProfile]]): [Principal, ExtendedUserProfile] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    user: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        user: value.user,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    status: _TournamentStatus;
    prizeDistribution: Array<bigint>;
    title: string;
    imageUrl: string;
    totalSlots: bigint;
    entryFee: bigint;
    slotsFilled: bigint;
    rules: string;
    prizePool: bigint;
}): {
    id: bigint;
    categoryId: bigint;
    status: TournamentStatus;
    prizeDistribution: Array<bigint>;
    title: string;
    imageUrl: string;
    totalSlots: bigint;
    entryFee: bigint;
    slotsFilled: bigint;
    rules: string;
    prizePool: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        status: from_candid_TournamentStatus_n18(_uploadFile, _downloadFile, value.status),
        prizeDistribution: value.prizeDistribution,
        title: value.title,
        imageUrl: value.imageUrl,
        totalSlots: value.totalSlots,
        entryFee: value.entryFee,
        slotsFilled: value.slotsFilled,
        rules: value.rules,
        prizePool: value.prizePool
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    user: Principal;
    txnType: {
        deposit: null;
    } | {
        withdrawal: null;
    } | {
        tournamentEntry: null;
    };
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    user: Principal;
    txnType: Variant_deposit_withdrawal_tournamentEntry;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        user: value.user,
        txnType: from_candid_variant_n25(_uploadFile, _downloadFile, value.txnType),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    paymentMethod: {
        easyPaisa: null;
    } | {
        jazzCash: null;
    };
    transactionReference: string;
    user: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    paymentMethod: Variant_easyPaisa_jazzCash;
    transactionReference: string;
    user: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_variant_n7(_uploadFile, _downloadFile, value.paymentMethod),
        transactionReference: value.transactionReference,
        user: value.user,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    upcoming: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "upcoming" in value ? TournamentStatus.upcoming : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
} | {
    tournamentEntry: null;
}): Variant_deposit_withdrawal_tournamentEntry {
    return "deposit" in value ? Variant_deposit_withdrawal_tournamentEntry.deposit : "withdrawal" in value ? Variant_deposit_withdrawal_tournamentEntry.withdrawal : "tournamentEntry" in value ? Variant_deposit_withdrawal_tournamentEntry.tournamentEntry : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ExtendedUserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ExtendedUserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easyPaisa: null;
} | {
    jazzCash: null;
}): Variant_easyPaisa_jazzCash {
    return "easyPaisa" in value ? Variant_easyPaisa_jazzCash.easyPaisa : "jazzCash" in value ? Variant_easyPaisa_jazzCash.jazzCash : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequest>): Array<DepositRequest> {
    return value.map((x)=>from_candid_DepositRequest_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_easyPaisa_jazzCash): {
    easyPaisa: null;
} | {
    jazzCash: null;
} {
    return value == Variant_easyPaisa_jazzCash.easyPaisa ? {
        easyPaisa: null
    } : value == Variant_easyPaisa_jazzCash.jazzCash ? {
        jazzCash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
