/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExtendedUserProfile {
    inGameName: string;
    username: string;
    balance: bigint;
    legendId: bigint;
    referCode: string;
    mobileNo: string;
    fullName: string;
    email: string;
    gameUID: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_deposit_withdrawal_tournamentEntry {
    deposit = "deposit",
    withdrawal = "withdrawal",
    tournamentEntry = "tournamentEntry"
}
export enum Variant_easyPaisa_jazzCash {
    easyPaisa = "easyPaisa",
    jazzCash = "jazzCash"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export type Time = bigint;
export interface Transaction {
    id: bigint;
    user: Principal;
    txnType: Variant_deposit_withdrawal_tournamentEntry;
    timestamp: Time;
    amount: bigint;
}
export interface LeaderboardEntry {
    player: Principal;
    score: bigint;
    tournamentId: bigint;
}
export enum TournamentStatus {
    active = "active",
    upcoming = "upcoming",
    completed = "completed"
}
export interface Tournament {
    id: bigint;
    categoryId: bigint;
    status: TournamentStatus;
    prizeDistribution: Array<bigint>;
    title: string;
    imageUrl: string;
    totalSlots: bigint;
    entryFee: bigint;
    slotsFilled: bigint;
    rules: string;
    prizePool: bigint;
}
export interface Category {
    id: bigint;
    name: string;
}
export interface DepositRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    paymentMethod: Variant_easyPaisa_jazzCash;
    transactionReference: string;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface WithdrawalRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface GlobalLeaderboardEntry {
    username: string;
    player: Principal;
    totalWinnings: bigint;
    totalScore: bigint;
}
export interface PaymentNumbers {
    easyPaisa: string;
    jazzCash: string;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoins(user: Principal, amount: bigint): Promise<void>;
    addCoinsByLegendId(legendId: bigint, amount: bigint): Promise<void>;
    approveDepositRequest(requestId: bigint): Promise<void>;
    approveWithdrawalRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(name: string): Promise<void>;
    createTournament(title: string, categoryId: bigint, entryFee: bigint, prizePool: bigint, totalSlots: bigint, rules: string, prizeDistribution: Array<bigint>, imageUrl: string): Promise<void>;
    getAllDepositRequests(): Promise<Array<DepositRequest>>;
    getAllUsers(): Promise<Array<[Principal, ExtendedUserProfile]>>;
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCallerDepositRequests(): Promise<Array<DepositRequest>>;
    getCallerJoinedSlot(tournamentId: bigint): Promise<bigint | null>;
    getCallerUserProfile(): Promise<ExtendedUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCategories(): Promise<Array<Category>>;
    getGlobalLeaderboard(): Promise<Array<GlobalLeaderboardEntry>>;
    getLeaderboard(tournamentId: bigint): Promise<Array<LeaderboardEntry>>;
    getPaymentNumbers(): Promise<PaymentNumbers>;
    getPendingDepositRequests(): Promise<Array<DepositRequest>>;
    getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getResetCode(): Promise<string>;
    getTakenSlots(tournamentId: bigint): Promise<Array<bigint>>;
    getTournament(id: bigint): Promise<Tournament | null>;
    getTournamentRoomDetails(tournamentId: bigint): Promise<{ roomPassword: string; roomId: string; } | null>;
    getTournaments(): Promise<Array<Tournament>>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUserByLegendId(legendId: bigint): Promise<[Principal, ExtendedUserProfile] | null>;
    getUserProfile(user: Principal): Promise<ExtendedUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: bigint, slotNumber: bigint): Promise<void>;
    login(email: string, passwordHash: string): Promise<{ __kind__: "ok"; ok: ExtendedUserProfile; } | { __kind__: "err"; err: string; }>;
    loginByLegendId(legendId: bigint, passwordHash: string): Promise<{ __kind__: "ok"; ok: ExtendedUserProfile; } | { __kind__: "err"; err: string; }>;
    postScores(tournamentId: bigint, scores: Array<[Principal, bigint]>): Promise<void>;
    registerAccount(email: string, passwordHash: string, fullName: string, inGameName: string, gameUID: string, mobileNo: string, referCode: string): Promise<{ __kind__: "ok"; ok: null; } | { __kind__: "err"; err: string; }>;
    registerUser(fullName: string, inGameName: string, gameUID: string, mobileNo: string, email: string, referCode: string): Promise<void>;
    rejectDepositRequest(requestId: bigint): Promise<void>;
    rejectWithdrawalRequest(requestId: bigint): Promise<void>;
    removeCoinsByLegendId(legendId: bigint, amount: bigint): Promise<void>;
    resetPassword(email: string, resetCode: string, newPasswordHash: string): Promise<{ __kind__: "ok"; ok: null; } | { __kind__: "err"; err: string; }>;
    resetPasswordByLegendId(legendId: bigint, resetCode: string, newPasswordHash: string): Promise<{ __kind__: "ok"; ok: null; } | { __kind__: "err"; err: string; }>;
    saveCallerUserProfile(profile: ExtendedUserProfile): Promise<void>;
    setPaymentNumbers(jazzCash: string, easyPaisa: string): Promise<void>;
    setResetCode(code: string): Promise<void>;
    setTournamentRoomDetails(tournamentId: bigint, roomId: string, roomPassword: string): Promise<void>;
    setUsername(username: string): Promise<void>;
    submitDepositRequest(amount: bigint, paymentMethod: Variant_easyPaisa_jazzCash, transactionReference: string): Promise<bigint>;
    submitWithdrawalRequest(amount: bigint): Promise<bigint>;
    updateUserInfo(fullName: string, inGameName: string, gameUID: string, mobileNo: string, email: string): Promise<void>;
}
import type { ExtendedUserProfile as _ExtendedUserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginByLegendId(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: ExtendedUserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginByLegendId(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginByLegendId(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordByLegendId(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordByLegendId(arg0, arg1, arg2);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordByLegendId(arg0, arg1, arg2);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCoins(user, amount) { return this.actor.addCoins(user, amount); }
    async addCoinsByLegendId(legendId, amount) { return this.actor.addCoinsByLegendId(legendId, amount); }
    async approveDepositRequest(requestId) { return this.actor.approveDepositRequest(requestId); }
    async approveWithdrawalRequest(requestId) { return this.actor.approveWithdrawalRequest(requestId); }
    async createCategory(name) { return this.actor.createCategory(name); }
    async createTournament(title, categoryId, entryFee, prizePool, totalSlots, rules, prizeDistribution, imageUrl) { return this.actor.createTournament(title, categoryId, entryFee, prizePool, totalSlots, rules, prizeDistribution, imageUrl); }
    async getAllDepositRequests() { const r = await this.actor.getAllDepositRequests(); return r.map(d => ({...d, status: 'pending' in d.status ? Variant_pending_approved_rejected.pending : 'approved' in d.status ? Variant_pending_approved_rejected.approved : Variant_pending_approved_rejected.rejected, paymentMethod: 'jazzCash' in d.paymentMethod ? Variant_easyPaisa_jazzCash.jazzCash : Variant_easyPaisa_jazzCash.easyPaisa})); }
    async getAllUsers() { return this.actor.getAllUsers(); }
    async getAllWithdrawalRequests() { const r = await this.actor.getAllWithdrawalRequests(); return r.map(d => ({...d, status: 'pending' in d.status ? Variant_pending_approved_rejected.pending : 'approved' in d.status ? Variant_pending_approved_rejected.approved : Variant_pending_approved_rejected.rejected})); }
    async getCallerDepositRequests() { const r = await this.actor.getCallerDepositRequests(); return r.map(d => ({...d, status: 'pending' in d.status ? Variant_pending_approved_rejected.pending : 'approved' in d.status ? Variant_pending_approved_rejected.approved : Variant_pending_approved_rejected.rejected, paymentMethod: 'jazzCash' in d.paymentMethod ? Variant_easyPaisa_jazzCash.jazzCash : Variant_easyPaisa_jazzCash.easyPaisa})); }
    async getCallerJoinedSlot(tournamentId) { const r = await this.actor.getCallerJoinedSlot(tournamentId); return (r && r.length > 0 && r[0] !== undefined) ? r[0] : null; }
    async getCallerUserProfile() { const r = await this.actor.getCallerUserProfile(); return (r && r.length > 0 && r[0] !== undefined) ? r[0] : null; }
    async getCallerWithdrawalRequests() { const r = await this.actor.getCallerWithdrawalRequests(); return r.map(d => ({...d, status: 'pending' in d.status ? Variant_pending_approved_rejected.pending : 'approved' in d.status ? Variant_pending_approved_rejected.approved : Variant_pending_approved_rejected.rejected})); }
    async getCategories() { return this.actor.getCategories(); }
    async getGlobalLeaderboard() { return this.actor.getGlobalLeaderboard(); }
    async getLeaderboard(tournamentId) { return this.actor.getLeaderboard(tournamentId); }
    async getPaymentNumbers() { return this.actor.getPaymentNumbers(); }
    async getPendingDepositRequests() { const r = await this.actor.getPendingDepositRequests(); return r.map(d => ({...d, status: Variant_pending_approved_rejected.pending, paymentMethod: 'jazzCash' in d.paymentMethod ? Variant_easyPaisa_jazzCash.jazzCash : Variant_easyPaisa_jazzCash.easyPaisa})); }
    async getPendingWithdrawalRequests() { const r = await this.actor.getPendingWithdrawalRequests(); return r.map(d => ({...d, status: Variant_pending_approved_rejected.pending})); }
    async getResetCode() { return this.actor.getResetCode(); }
    async getTakenSlots(tournamentId) { return this.actor.getTakenSlots(tournamentId); }
    async getTournament(id) { const r = await this.actor.getTournament(id); if (!r || r.length === 0 || r[0] === undefined) return null; const t = r[0]; return {...t, status: 'active' in t.status ? TournamentStatus.active : 'completed' in t.status ? TournamentStatus.completed : TournamentStatus.upcoming}; }
    async getTournamentRoomDetails(tournamentId) { const r = await this.actor.getTournamentRoomDetails(tournamentId); return (r && r.length > 0 && r[0] !== undefined) ? r[0] : null; }
    async getTournaments() { const r = await this.actor.getTournaments(); return r.map(t => ({...t, status: 'active' in t.status ? TournamentStatus.active : 'completed' in t.status ? TournamentStatus.completed : TournamentStatus.upcoming})); }
    async getTransactionHistory() { const r = await this.actor.getTransactionHistory(); return r.map(t => ({...t, txnType: 'deposit' in t.txnType ? Variant_deposit_withdrawal_tournamentEntry.deposit : 'withdrawal' in t.txnType ? Variant_deposit_withdrawal_tournamentEntry.withdrawal : Variant_deposit_withdrawal_tournamentEntry.tournamentEntry})); }
    async getUserByLegendId(legendId) { const r = await this.actor.getUserByLegendId(legendId); return (r && r.length > 0 && r[0] !== undefined) ? r[0] : null; }
    async getUserProfile(user) { const r = await this.actor.getUserProfile(user); return (r && r.length > 0 && r[0] !== undefined) ? r[0] : null; }
    async joinTournament(tournamentId, slotNumber) { return this.actor.joinTournament(tournamentId, slotNumber); }
    async login(email, passwordHash) { const r = await this.actor.login(email, passwordHash); return 'ok' in r ? ({__kind__: 'ok' as const, ok: r.ok}) : ({__kind__: 'err' as const, err: r.err}); }
    async postScores(tournamentId, scores) { return this.actor.postScores(tournamentId, scores); }
    async registerAccount(email, passwordHash, fullName, inGameName, gameUID, mobileNo, referCode) { const r = await this.actor.registerAccount(email, passwordHash, fullName, inGameName, gameUID, mobileNo, referCode); return 'ok' in r ? ({__kind__: 'ok' as const, ok: null}) : ({__kind__: 'err' as const, err: r.err}); }
    async registerUser(fullName, inGameName, gameUID, mobileNo, email, referCode) { return this.actor.registerUser(fullName, inGameName, gameUID, mobileNo, email, referCode); }
    async rejectDepositRequest(requestId) { return this.actor.rejectDepositRequest(requestId); }
    async rejectWithdrawalRequest(requestId) { return this.actor.rejectWithdrawalRequest(requestId); }
    async removeCoinsByLegendId(legendId, amount) { return this.actor.removeCoinsByLegendId(legendId, amount); }
    async resetPassword(email, resetCode, newPasswordHash) { const r = await this.actor.resetPassword(email, resetCode, newPasswordHash); return 'ok' in r ? ({__kind__: 'ok' as const, ok: null}) : ({__kind__: 'err' as const, err: r.err}); }
    async saveCallerUserProfile(profile) { return this.actor.saveCallerUserProfile(profile); }
    async setPaymentNumbers(jazzCash, easyPaisa) { return this.actor.setPaymentNumbers(jazzCash, easyPaisa); }
    async setResetCode(code) { return this.actor.setResetCode(code); }
    async setTournamentRoomDetails(tournamentId, roomId, roomPassword) { return this.actor.setTournamentRoomDetails(tournamentId, roomId, roomPassword); }
    async setUsername(username) { return this.actor.setUsername(username); }
    async submitDepositRequest(amount, paymentMethod, transactionReference) { const pm = paymentMethod === Variant_easyPaisa_jazzCash.jazzCash ? {jazzCash: null} : {easyPaisa: null}; return this.actor.submitDepositRequest(amount, pm, transactionReference); }
    async submitWithdrawalRequest(amount) { return this.actor.submitWithdrawalRequest(amount); }
    async updateUserInfo(fullName, inGameName, gameUID, mobileNo, email) { return this.actor.updateUserInfo(fullName, inGameName, gameUID, mobileNo, email); }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ExtendedUserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ExtendedUserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
